apiVersion: 'apps/v1'
kind: Pod
metadata:
  name: chat-db-pod
  labels:
    app: mongo
spec:
  containers:
    - name: mongo-db
      image: mongo:latest
      ports: 
        - containerPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
 