apiVersion: 'v1'
kind: Service
metadata:
  name: chat-app-service
  labels:
    app: chat-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008
  selector:
    app: chat-app
